version: 2.1

orbs:
  node: circleci/node@5.0.0
  aws-s3: circleci/aws-s3@3.0.0

jobs:
  prepare:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - node/install-packages
      - persist_to_workspace: 
          root: .
          paths:
            - .
  lint:
    docker:
      - image: cimg/node:lts
    steps:
      - attach_workspace: 
          at: .
      - run: npm run lint
  build:
    docker:
      - image: cimg/node:lts
    steps:
      - attach_workspace:
          at: .
      - run: npm run build
      - persist_to_workspace: 
          root: .
          paths:
            - dist
  publish-to-staging:
    docker:
      - image: cimg/python:3.6
    steps:
      - attach_workspace: 
          at: .
      - aws-s3/sync:
          from: dist
          to: "s3://$AWS_STAGING_S3_BUCKET_NAME"
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
  publish-to-production:
    docker:
      - image: cimg/python:3.6
    steps:
      - attach_workspace: 
          at: .
      - aws-s3/sync:
          from: dist
          to: "s3://$AWS_PRODUCTION_S3_BUCKET_NAME"
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"

workflows:
  build-and-publish:
    jobs:
      - prepare
      - lint:
          requires: 
            - prepare
      - build:
          requires:
            - prepare
      - publish-to-staging:
          requires:
            - lint
            - build
      - publish-to-production:
          requires:
            - lint
            - build
          filters: 
            branches:
              only: master

