version: 2.1

orbs:
  node: circleci/node@5.0.0

jobs:
  prepare:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - node/install-packages
      - persist_to_workspace: 
          root: .
          paths:
            - .
  lint:
    docker:
      - image: cimg/node:lts
    steps:
      - attach_workspace: 
          at: .
      - run: npx eslint .
  build:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - node/install-packages
      - run: npm run build
      - persist_to_workspace: 
          root: .
          paths:
            - dist
  publish-to-staging:
    docker:
      - image: cimg/node:lts
    steps:
      - attach_workspace: 
          at: .
      - run: ls -lah dist

workflows:
  publish:
    jobs:
      - prepare
      - lint:
          requires: 
            - prepare
      - build:
          requires:
            - prepare
      - publish-to-staging:
          requires:
            - build

